### ISSUE TITLE
Support install mirrorctl using brew

### ISSUE THREAD

**Issue by jeyraof** [hellodhlyn/mirrorctl#1]
I think this project is very valuable for many users like me :smile:
So supporting installing it by brew is such helpful!

### How to?
1. create [hellodhlyn/homebrew-mirrorctl](https://github.com/hellodhlyn/homebrew-mirrorctl) repository.
2. make formula code
3. then, you can install it:
    ```bash
    brew tap hellodhlyn/mirrorctl
    brew install mirrorctl
    ```

### example formula code:
```ruby
class MirrorCTL < Formula
  desc 'Manage mirror urls for many repositories.'
  homepage 'https://github.com/hellodhlyn/mirrorctl'
  version "0.1.0"

  if OS.mac?
    url "https://github.com/hellodhlyn/mirrorctl/releases/download/v0.1.0/mirrorctl-v0.1.0-darwin-amd64.tar.gz"
    sha256 "118d18d40b438ff56320d25c67e3dd330b56a56835b898cb633674cf385dd919"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/hellodhlyn/mirrorctl/releases/download/v0.1.0/mirrorctl-v0.1.0-linux-amd64.tar.gz"
      sha256 "10e145926a4b5e17769ab8f64edbbcfe664f21a3bd3820c5e0f4afe82a2e2baf"
    end
  end

  def install
    bin.install 'mirrorctl'
  end
end
```

There is some modifications needed, but you can easily support it.
Many thanks!

**Comment by jeyraof** [comment]
And manual for Brew Tap is [here](https://docs.brew.sh/Taps) ! 🎉

**Comment by hellodhlyn** [comment]
Just added a homebrew tap [hellodhlyn/mirrorctl](https://github.com/hellodhlyn/homebrew-mirrorctl).
Thanks for your suggestion and enjoy it!
